### ISSUE TITLE
About TravisCI build is broken due to MD lint bug

### ISSUE THREAD

**Issue by felixfaassen** [publiccodenet/about#737]
As you can see a number of pull requests fail on build:

#734 
#736 

The build error reports:

> 
> 1: from /home/travis/build/publiccodenet/about/vendor/bundle/ruby/2.5.0/gems/mdl-0.10.0/lib/mdl/doc.rb:50:in `new_from_file'
> 
> /home/travis/build/publiccodenet/about/vendor/bundle/ruby/2.5.0/gems/mdl-0.10.0/lib/mdl/doc.rb:50:in `read': No such file or directory @ rb_sysopen - CODE_OF_CONDUCT.md (Errno::ENOENT)
> 
> The command "./script/cibuild.sh" exited with 1.

The file exists and there are no new line characters in the filename. Diving into the problem I found that since 8 days there is an issue in MD lint which might cause this problem: https://github.com/markdownlint/markdownlint/issues/339 (
mdl v0.10.0 git-recurse flag is having issues)

It has been fixed 16 hours ago so I'm trying to find a way how we can force TravisCI to use the MD lint which includes this fix

**Comment by felixfaassen** [comment]
I can confirm this is the issue. I now instructed bundler to to build MDL from source which includes the recurssion fix and I'm able to make a successful build (gem 'mdl', :git => 'https://github.com/markdownlint)

2 possible solutions:

- Temporarily build mdl from source until they release a new version which include the fix
- Wait for the fix

**Comment by felixfaassen** [comment]
@jaymzh Thank you so much for letting us know!  Thank you so much for all your work on MDL.

**Comment by felixfaassen** [comment]
MD linter v 0.11.0 is available and solves bug
